### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by AmateurPlay** [VBitsHub/elegoo_moonraker#2]
Hi. When I connected to the printer via WinSCP, I did not find the **~/moonraker** directory, let alone the subsequent folders. Could you tell me more about the installation?
![Снимок экрана 2024-09-02 010118](https://github.com/user-attachments/assets/0098dd0b-bc23-4f3a-ac64-08ffb5f5738b)

**Comment by AmateurPlay** [comment]
I'm sorry for the stupidity. The source code contained a script for installation (as far as I understood). From there, I learned the full path

> **/home/mks/moonraker/moonraker/components/file_manager/**

Fluidd now displays metadata and a thumbnail.

However, there is no metadata on the thumbnail. I use OrcaSlicer 2.1.1 with a thumbnail of 300x300/PNG. Perhaps some special settings are required for OrcaSlicer so that the script has the right condition for the correct thumbnail with metadata?

**Comment by VBitsHub** [comment]
Sorry for the late reply, ~ for linux refers to the home folder, in this case you are correct, it is /home/mks. As for the thumbnail with metadata, you are referring to the touchpad? It should automatically show if you are using the latest files. If it is not showing, you can try changing the resolution of the thumbnail to 600x600/PNG or try changing the position of the texts in the metadata.py file

**Comment by AmateurPlay** [comment]
Hello again. I was referring to displaying the thumbnail in Fluidd.
![Снимок экрана 2024-09-05 070040](https://github.com/user-attachments/assets/fb9b2ef9-719d-4720-8c2a-384e0f4e56dc)
When printing starts, the sketch with the metadata is displayed as expected.
![photo_2024-09-05_07-01-50](https://github.com/user-attachments/assets/ffdb6f8f-d3a9-4257-a417-a60c71337d8b)

Perhaps I misunderstood the script? After a longer processing, when loading g-code through the web interface, I thought that the thumbnail used in the slicer was changing and displayed with metadata. But it looks like it only works when printing starts.

It would be more convenient to view this information in Fluid, for example, to track the same parts, but with different parameters.

**Comment by VBitsHub** [comment]
Unfortunately the thumbnail in fluidd does not include the 3 meta data information like on the touch screen as they can be seen in the file statistic screen within fluidd. The meta data can be seen in the jobs area of fluidd next to the image itself, you may need to setup the fluidd gui to show additional metadata on the page as it is defaulted to hide it and only show specific ones by fluidd default.
